# Introduction to *numpy* library

Data Science  
TECNUN - Escuela de Ingeniería  
Universidad de Navarra

- Idoia Ochoa: iochoal@unav.es



First, we will load the library and label it as `np`.

In [1]:
import numpy as np

The `numpy` module works with objects of the `numpy arrays` class. They are created as shown below:

In [2]:
D1 = np.array([1, 2, 3])
D2 = np.array([(1,2,3), (4,5,6)])
D3 = np.array([[(1,2,3), (4,5,6)], [(7,8,9), (10,11,12)]])

In [3]:
print(D1)
print('\n')
print(D2)
print('\n')
print(D3)

[1 2 3]


[[1 2 3]
 [4 5 6]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Additionally, we can create some specific types of arrays with predefined numpy functions.

- np.zeros(): Array of zeros with the dimensions specified as an argument.
- np.ones(): Array of ones with the dimensions specified as an argument.
- np.arange(): 1D array. The lower limit, upper limit, and step are set as arguments.
- np.linspace(): 1D array. The lower limit, upper limit, and number of elements are set as arguments.
- np.full(): Array of a specified value as an argument. The dimensions are also set as an input argument.
- np.eye(): 2D identity array with dimensions specified as an argument.
- np.random.random(): Array of random numbers with dimensions specified as an argument.
- np.empty(): Empty array with dimensions specified as an argument.

In [15]:
print(np.arange(2,36,3))
print('\n')
print(np.linspace(0,11,20))
print(np.ones((2, 1)))
print(np.random.random((2, 1)))


[ 2  5  8 11 14 17 20 23 26 29 32 35]


[ 0.          0.57894737  1.15789474  1.73684211  2.31578947  2.89473684
  3.47368421  4.05263158  4.63157895  5.21052632  5.78947368  6.36842105
  6.94736842  7.52631579  8.10526316  8.68421053  9.26315789  9.84210526
 10.42105263 11.        ]
[[1.]
 [1.]]
[[0.56217119]
 [0.61896039]]


Arrays have attributes and methods that can be very useful for obtaining information about the objects.

- array.shape: Size of the array.
- len(array): Length of the array.
- array.ndim: Number of dimensions of the array.
- array.size: Number of elements in the array.
- array.dtype: Type of elements in the array.
- array.astype(): Converts the elements of the array to the type we specify as an argument.


In [18]:
D1 = np.array([1, 2, 3])
D2 = np.array([(1,2,3), (4,5,6)])
D3 = np.array([[(1,2,3), (4,5,6)], [(7,8,9), (10,11,12)]])

print(D3.shape)
print('\n')
print(D3.ndim)
print('\n')
print(D3.size)
print('\n')
print(D3.dtype)
print('\n')
print(D3.astype(float))


(2, 2, 3)


3


12


int64


[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


Aside from the operators `+`, `-`, `*`, and `/`, the module provides functions to perform these types of operations.



In [19]:
array1 = np.array([5, 6, 2, 4])
array2 = np.array([1, 3, 8, 2])

In [20]:
print(np.add(array1, array2))
print('\n')
print(np.subtract(array1, array2))
print('\n')
print(np.multiply(array1, array2))

[ 6  9 10  6]


[ 4  3 -6  2]


[ 5 18 16  8]


`numpy` allows comparisons between elements of its arrays.

In [21]:
array1 = np.array([5, 6, 2, 4])
array2 = np.array([1, 6, 8, 2])
array3 = np.array([1, 6, 8, 2])

print(array1 == array2) # element by element
print('\n')
print(array1 > array2)
print('\n')




[False  True False False]


[ True False False  True]


False


It is also possible to check if two arrays are equal or not.

In [22]:
print(np.array_equal(array1, array3)) # this one compares all elements in the array


False


Here are some other functions we can use:

In [23]:
array1 = np.array([1, 6, 8, 2])

print(array1.sum())
print('\n')
print(array1.min())
print('\n')
print(array1.max(axis=0)) # axis argument useful if you have more than one dimension in the array, e.g., to specify rows or columns
print('\n')
print(array1.cumsum(axis=0))

17


1


8


[ 1  7 15 17]


We can access the elements of arrays in the following way:

In [27]:
D1 = np.array([1, 2, 3])
D2 = np.array([(1,2,3), (4,5,6)])
D3 = np.array([[(1,2,3), (4,5,6)], [(7,8,9), (10,11,12)]])

print(D1)
print('\n')
print(D2)
print('\n')
print(D3)


[1 2 3]


[[1 2 3]
 [4 5 6]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [30]:
print(D1[1]) # here we need to specify the index of 1 dimension
print('\n')
print(D2[1, 2]) # here we need to specify the index of the 2 dimensions
print('\n')
print(D3[1, 0, 1]) # here we need to specify the index of the 3 dimensions

2


6


8


To obtain slices of the arrays, we will do the following:

In [25]:
print(D1)
print('\n')
print(D2)
print('\n')
print(D3)

[1 2 3]


[[1 2 3]
 [4 5 6]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
print(D1[0:2])
print('\n')
print(D2[0:2, 1])

[1 2]


[2 5]


You can obtain slices of arrays conditionally.

In [34]:
print(D3>5)
print(D3[D3>5])

[[[False False False]
  [False False  True]]

 [[ True  True  True]
  [ True  True  True]]]
[ 6  7  8  9 10 11 12]


And, finally, we can access arrays by selecting the position in each of the axes.

In [35]:
print(D1)
print('\n')
print(D2)
print('\n')
print(D3)

[1 2 3]


[[1 2 3]
 [4 5 6]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [38]:
print(D1[[1]])
print('\n')
print(D2[[1, 0, 1, 1], [0, 1, 2, 0]]) # This will return elements (1,0) -> 4, (0,1) -> 2, (1,2) and (1,0)
print('\n')
print(D3[[1, 0, 1, 1], [0, 1, 0, 0], [0, 2, 2, 1]])

[2]


[4 2 6 4]


[7 6 9 8]


There are a variety of functions shown in the `CheatSheet` distributed in class.